### ISSUE TITLE
Policy Files Not Being Detected

### ISSUE THREAD

**Issue by paulmccrady** [Azure/manage-azure-policy#24]
Hi, I've created the following:

```
/root
../policies
../../check-storage-account-location
../../../assign.DEV.json
../../../policy.json
```

Yet the action reports:

**_Warning: Did not find any policies to create/update. No policy files match the given patterns or no changes were detected. If you have policy definitions or policy initiatives, please ensure that the files are named 'policy.json' and 'policyset.json' respectively._**

... and no policy is created in my subscription. Can someone double check the dir/file setup above it correct ? Is there anything within the policy/assignment files themselves that might stop the action from working?

I'm using the action as follows:

```
      - name: Create or Update Azure Policies
        uses: azure/manage-azure-policy@v0
        with:      
          paths: |                  
            policies/**  # path to directory where policy files were downloaded in runner
```

**Comment by tauhid621** [comment]
@paulmccrady Do the json files contain id, type, name and properties fields?

Also, are you using checkout action before invoking the manage-azure-policy action? In case you are using it, are you checking out to some other path?

   - name: Checkout
      uses: actions/checkout@v2

**Comment by paulmccrady** [comment]
@tauhid621 policy below

```
{  
  "properties": {
    "displayName": "Check Storage Account Location",
    "policyType": "Custom",
    "mode": "All",
    "description": "Force resources to be deployed to UK South",
    "metadata": {
      "category": "Storage"
    }
  },
  "parameters": {
    "allowedLocation": {
      "type": "string",
      "metadata": {
        "description": "The allowed location for resources.",
        "displayName": "Allowed location",
        "strongType": "location"
      }
    }
  },
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Storage/storageAccounts"
      },
      {
        "not": {
          "field": "location",
          "equals": "[parameters('allowedLocation')]"
        }      
      }
    ]
  },
  "then": {
    "effect": "Audit"
  },
  "id": "/subscriptions/__subscriptionId__/providers/Microsoft.Authorization/policyDefinitions/__policyName__",
  "type": "Microsoft.Authorization/policyDefinitions",
  "name": "Check Storage Account Location"
}
```

First steps in pipeline are 

```
    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["**/*.json"]'
        env:
          subscriptionId: $env:subscription_id
          policyName: $env:policy_name
```

Thanks for the assistance
